//
//  ProductListWorker.swift
//  obdshop
//
//  Created by baizheng on 22/11/2017.
//  Copyright (c) 2017 baizheng. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ProductListWorker
{
  func doSomeWork()
  {
  }
}
